apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-serving-sa
  namespace: ml-serving
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ml-serving-role
  namespace: ml-serving
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""] 
    resources: ["services"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ml-serving-rolebinding
  namespace: ml-serving
subjects:
  - kind: ServiceAccount
    name: ml-serving-sa
    namespace: ml-serving
roleRef:
  kind: Role
  name: ml-serving-role
  apiGroup: rbac.authorization.k8s.io
